### ISSUE TITLE
Migrate to Node 18

### ISSUE THREAD

**Issue by gonzalojaubert** [boostercloud/booster#1415]
## Description

Booster uses Node 16 version. This version will reach the EOL at 2023-09-11.

Release | Status | Codename | Initial Release | Active LTS Start | Maintenance Start | End-of-life
-- | -- | -- | -- | -- | -- | --
16.x | Maintenance | Gallium | 2021-04-20 | 2021-10-26 | 2022-10-18 | 2023-09-11

https://github.com/nodejs/release#release-schedule

![image](https://github.com/boostercloud/booster/assets/111118818/9ffa5fdb-47b4-4404-b8af-b0e931114b72)

## Possible Solution

Update Booster node version to 18 and all needed libraries.

**Comment by gonzalogarciajaubert** [comment]
Unit test Github action had been failing due to Node 16 warning while running **aws-infrastructure** unit tests. In commit https://github.com/boostercloud/booster/commit/bdd3c3ca537638ff7de134c58e7299f585aef8ea#diff-548dc534cd80fb7795092faaf28b3d13e17964e46292327b031b68b90c3967ed the tests were disabled. When the migration is complete we will need to enable them again.

**Comment by javiertoledo** [comment]
This will be released in the upcoming v2.0.0 version. See the branch #1460 to learn more about next major release status.
