### ISSUE TITLE
Local Provider missing dependency

### ISSUE THREAD

**Issue by Fecony** [boostercloud/booster#623]
# Bug Report

When using Local Provider and running it with `boost start -e <environment>` it throws error about missing `@types/nedb` dependency. Because `@types/nedb` is only listed as devDependency in Local Provider package.

![image](https://user-images.githubusercontent.com/36774784/108823105-acec2c00-75c8-11eb-8779-7aec0d5dc104.png)

## Current Behavior

Clear project is throwing error when starting with local provider `boost start -e <environment>` 

## Expected behavior

When starting `boost start -e <environment>` with local provider it generates code and starts server without errors.

## Possible Solution

Add `@types/nedb` as dependency to Local Provider

### Environment

- Booster version: 0.11.3
- Node/npm version: v14.13.1 / 7.5.2
- OS: OSX 11.2

**Comment by NickSeagull** [comment]
Thanks for reporting!

**Comment by sachinh19** [comment]
As one of my first issues on GitHub I thought of taking a go at this since it is a one line change.

But I need a little guidance on testing this one. The change is pretty simple as I was able to follow the contribution guidelines to get dependencies installed, made the one line change of moving  `@types/nedb` devDependencies to dependencies. Got the `check-all-the-things` and `lerna run test` commands to succeed.

What I am unable to do is test the scenario explained above by running `boost start -e <environment>`. Is there some special setup I need to get this command to work?

**Comment by NickSeagull** [comment]
Hey @sachinh19 ! This is because when you do a `boost start ...` it will use the already created project, which will use the already published changes in `npm` to test it, there's a bit more of ceremony. If you want, submit the PR, and I'll test it for you

**Comment by sachinh19** [comment]
Sounds good. I'll submit the PR in some time!
