### ISSUE TITLE
Provider loading other providers config when multicloud

### ISSUE THREAD

**Issue by adriangmweb** [boostercloud/booster#763]
# Bug Report

## Current Behavior

When there are several providers in different environments in the config file, every provider loads not just its own configuration, but also the configuration of the rest of them. This can cause errors when there are specific dependencies on one provider that is not available on the rest.

## Expected behavior

Every provider should just load its own configuration.

## Possible Solution

Refactor the config file to not load a provider config until it's being used.

### Environment

- Booster version: [e.g. 0.14.1]

**Comment by javiertoledo** [comment]
The error is here: https://github.com/boostercloud/booster/blob/main/packages/framework-provider-aws/package.json#L41

In my opinion, `aws-sdk` should not be a devDependency, a devDependency is an auxiliary package that's only used in the developer's machine, but this package is required and actively used by the `framework-provider-aws` package, and it can't work without it.

I understand that we put `aws-sdk` in devDependencies because we assume that this package is only used in AWS and we know that the package is available in the lambda environment, but removing this package is just an optimization that in my opinion should be done at deploy time. It naturally belongs to `dependencies`.

**Comment by adriangmweb** [comment]
You are right! But still, I think that the ideal solution should be that a provider just loads its own config, so no one but aws would need `aws-sdk` and it can remain on `devDependencies` which will make deployments much lighter.

**Comment by javiertoledo** [comment]
Check out the `optionalDependencies` option in NPM, it seems perfect for this use case https://docs.npmjs.com/cli/v7/configuring-npm/package-json#optionaldependencies

**Comment by adriangmweb** [comment]
Closing this as it was solved in #816
